services:
  ddiregistry:
    image: ddiregistry:local
    container_name: ddiregistry
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      # DATABASE
      ConnectionStrings__DefaultConnection: "Host=db;Database=ddi_registry;Username=postgres;Password=postgres;"
    ports:
      - "8000:80"
    depends_on:
      - db

  # -----------------------------------------------------
  # POSTGRES DATABASE
  # -----------------------------------------------------
  db:
    image: postgres:17-alpine
    container_name: db

    # Variables propres au service Postgres uniquement
    environment:
      POSTGRES_DB: ddi_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ddi_registry_postgres_data:/var/lib/postgresql/data

# ---------------------------------------------------------
# VOLUMES
# ---------------------------------------------------------
volumes:
  ddi_registry_postgres_data:
